<script setup lang="ts">
import PageHeader from '../../components/common/PageHeader.vue'; import { useForm } from 'vee-validate'; import { toTypedSchema } from '@vee-validate/zod'; import { departmentSchema } from '../../schemas/forms.schema';
import { computed, onMounted, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { createDepartment, getDepartment, updateDepartment } from '../../services/departments.service'; import { listCompanies } from '../../services/companies.service'; import type { Company } from '../../types/company.types';
const { setValues, validate } = useForm({ validationSchema: toTypedSchema(departmentSchema) });
const route = useRoute(); const router = useRouter(); const id = computed(() => route.params.id as string | undefined); const editing = computed(() => !!id.value); const readonly = computed(() => route.meta.mode === 'view'); const loading = ref(false); const saving = ref(false); const error = ref(''); const companies = ref<Company[]>([]); const form = ref({ name: '', code: '', companyId: '' });
async function load() { loading.value = true; try { companies.value = await listCompanies(); if (id.value) { const item = await getDepartment(id.value); form.value = { name: item.name, code: item.code, companyId: '' }; } } catch { error.value = 'Não foi possível carregar o setor.'; } finally { loading.value = false; } }
async function save() { setValues(form.value as any); const result = await validate(); if (!result.valid) { error.value = 'Revise os campos destacados antes de salvar.'; return; } saving.value = true; try { const payload = { ...form.value, companyId: form.value.companyId || undefined }; if (editing.value) await updateDepartment(id.value!, payload); else await createDepartment(payload); router.push('/settings/departments'); } catch (err: any) { error.value = err?.response?.data?.message ?? 'Não foi possível salvar o setor.'; } finally { saving.value = false; } } onMounted(load);
</script>
<template><div><PageHeader :title="readonly ? 'Visualizar setor' : editing ? 'Editar setor' : 'Novo setor'" back-to="/settings/departments" /><v-alert v-if="error" type="error" density="compact" class="mb-4">{{ error }}</v-alert><v-card :loading="loading"><v-card-text><v-text-field v-model="form.name" label="Nome" :readonly="readonly" /><v-text-field v-model="form.code" label="Código" :readonly="readonly" /><v-select v-model="form.companyId" :items="companies" item-title="name" item-value="id" label="Empresa" clearable :readonly="readonly" /></v-card-text><v-card-actions><v-spacer /><v-btn variant="outlined" @click="router.push('/settings/departments')">{{ readonly ? 'Voltar' : 'Cancelar' }}</v-btn><v-btn v-if="!readonly" color="primary" variant="outlined" :loading="saving" :disabled="!form.name || !form.code" @click="save">Salvar</v-btn></v-card-actions></v-card></div></template>
