import type { RouteRecordRaw } from 'vue-router';

// Rotas protegidas da plataforma, servidas pelo DefaultLayout (menu lateral
// + top bar). Todas exigem sessão autenticada (meta.requiresAuth).
const dashboardRouter: RouteRecordRaw[] = [
  {
    path: '/',
    component: () => import('../layouts/DefaultLayout.vue'),
    meta: { requiresAuth: true },
    children: [
      { path: '', name: 'dashboard', component: () => import('../views/DashboardView.vue'), meta: { title: 'Dashboard' } },
      { path: 'inbox', name: 'inbox', component: () => import('../views/ComingSoonView.vue'), meta: { title: 'Inbox' } },
      { path: 'tickets', name: 'tickets', component: () => import('../views/ComingSoonView.vue'), meta: { title: 'Tickets' } },
      { path: 'contacts', name: 'contacts', component: () => import('../views/contacts/ContactsView.vue'), meta: { title: 'Contatos', permission: 'contacts.read' } },
      { path: 'contacts/new', name: 'contacts-new', component: () => import('../views/contacts/ContactFormView.vue'), meta: { title: 'Novo contato', permission: 'contacts.manage' } },
      { path: 'contacts/:id/edit', name: 'contacts-edit', component: () => import('../views/contacts/ContactFormView.vue'), meta: { title: 'Editar contato', permission: 'contacts.manage' } },
      { path: 'contacts/:id/view', name: 'contacts-view', component: () => import('../views/contacts/ContactFormView.vue'), meta: { title: 'Visualizar contato', permission: 'contacts.read', mode: 'view' } },
      { path: 'companies', name: 'companies', component: () => import('../views/companies/CompaniesView.vue'), meta: { title: 'Empresas', permission: 'companies.read' } },
      { path: 'companies/new', name: 'companies-new', component: () => import('../views/companies/CompanyFormView.vue'), meta: { title: 'Nova empresa', permission: 'companies.manage' } },
      { path: 'companies/:id/edit', name: 'companies-edit', component: () => import('../views/companies/CompanyFormView.vue'), meta: { title: 'Editar empresa', permission: 'companies.manage' } },
      { path: 'companies/:id/view', name: 'companies-view', component: () => import('../views/companies/CompanyFormView.vue'), meta: { title: 'Visualizar empresa', permission: 'companies.read', mode: 'view' } },
      { path: 'business-partners', name: 'business-partners', component: () => import('../views/business-partners/BusinessPartnersView.vue'), meta: { title: 'Clientes e fornecedores', permission: 'business_partners.read' } },
      { path: 'business-partners/new', name: 'business-partners-new', component: () => import('../views/business-partners/BusinessPartnerFormView.vue'), meta: { title: 'Novo parceiro', permission: 'business_partners.manage' } },
      { path: 'business-partners/:id/edit', name: 'business-partners-edit', component: () => import('../views/business-partners/BusinessPartnerFormView.vue'), meta: { title: 'Editar parceiro', permission: 'business_partners.manage' } },
      { path: 'business-partners/:id/view', name: 'business-partners-view', component: () => import('../views/business-partners/BusinessPartnerFormView.vue'), meta: { title: 'Visualizar parceiro', permission: 'business_partners.read', mode: 'view' } },
      { path: 'stock/products', name: 'stock-products', component: () => import('../views/ComingSoonView.vue'), meta: { title: 'Produtos' } },
      { path: 'stock/warehouses', name: 'stock-warehouses', component: () => import('../views/ComingSoonView.vue'), meta: { title: 'Depósitos' } },
      { path: 'stock/balances', name: 'stock-balances', component: () => import('../views/ComingSoonView.vue'), meta: { title: 'Saldo de estoque' } },
      { path: 'stock/entries', name: 'stock-entries', component: () => import('../views/ComingSoonView.vue'), meta: { title: 'Entradas de produto' } },
      { path: 'stock/exits', name: 'stock-exits', component: () => import('../views/ComingSoonView.vue'), meta: { title: 'Saídas de produto' } },
      { path: 'stock/counts', name: 'stock-counts', component: () => import('../views/ComingSoonView.vue'), meta: { title: 'Inventário' } },
      { path: 'analytics', name: 'analytics', component: () => import('../views/ComingSoonView.vue'), meta: { title: 'Análises' } },
      {
        path: 'platform/tenants',
        name: 'platform-tenants',
        component: () => import('../views/tenants/TenantsView.vue'),
        meta: { title: 'Tenants', permission: 'tenants.read' },
      },
      {
        path: 'platform/tenants/new',
        name: 'platform-tenants-new',
        component: () => import('../views/tenants/TenantFormView.vue'),
        meta: { title: 'Novo tenant', permission: 'tenants.manage' },
      },
      {
        path: 'platform/tenants/:id/edit',
        name: 'platform-tenants-edit',
        component: () => import('../views/tenants/TenantFormView.vue'),
        meta: { title: 'Editar tenant', permission: 'tenants.manage' },
      },
      {
        path: 'platform/tenants/:id/view',
        name: 'platform-tenants-view',
        component: () => import('../views/tenants/TenantDetailsView.vue'),
        meta: { title: 'Detalhes do tenant', permission: 'tenants.read' },
      },
      { path: 'integrations/api-clients', name: 'integrations-api-clients', component: () => import('../views/ComingSoonView.vue'), meta: { title: 'API keys' } },
      { path: 'integrations/webhooks', name: 'integrations-webhooks', component: () => import('../views/ComingSoonView.vue'), meta: { title: 'Webhooks / n8n' } },
      { path: 'integrations/docs', name: 'integrations-docs', component: () => import('../views/ComingSoonView.vue'), meta: { title: 'Documentação da API' } },
      { path: 'settings/departments', name: 'settings-departments', component: () => import('../views/departments/DepartmentsView.vue'), meta: { title: 'Setores e equipes', permission: 'departments.read' } },
      { path: 'settings/departments/new', name: 'settings-departments-new', component: () => import('../views/departments/DepartmentFormView.vue'), meta: { title: 'Novo setor', permission: 'departments.manage' } },
      { path: 'settings/departments/:id/edit', name: 'settings-departments-edit', component: () => import('../views/departments/DepartmentFormView.vue'), meta: { title: 'Editar setor', permission: 'departments.manage' } },
      { path: 'settings/departments/:id/view', name: 'settings-departments-view', component: () => import('../views/departments/DepartmentFormView.vue'), meta: { title: 'Visualizar setor', permission: 'departments.read', mode: 'view' } },
      { path: 'settings/channels', name: 'settings-channels', component: () => import('../views/channels/ChannelsView.vue'), meta: { title: 'Canais', permission: 'channels.read' } },
      { path: 'settings/channels/new', name: 'settings-channels-new', component: () => import('../views/channels/ChannelFormView.vue'), meta: { title: 'Novo canal', permission: 'channels.manage' } },
      { path: 'settings/channels/:id/edit', name: 'settings-channels-edit', component: () => import('../views/channels/ChannelFormView.vue'), meta: { title: 'Editar canal', permission: 'channels.manage' } },
      { path: 'settings/channels/:id/view', name: 'settings-channels-view', component: () => import('../views/channels/ChannelFormView.vue'), meta: { title: 'Visualizar canal', permission: 'channels.read', mode: 'view' } },
      {
        path: 'settings/users',
        name: 'settings-users',
        component: () => import('../views/users/UsersView.vue'),
        meta: { title: 'Usuários e papéis', permission: 'users.read' },
      },
      {
        path: 'settings/users/new',
        name: 'settings-users-new',
        component: () => import('../views/users/UserFormView.vue'),
        meta: { title: 'Novo usuário', permission: 'users.manage' },
      },
      {
        path: 'settings/users/:id/edit',
        name: 'settings-users-edit',
        component: () => import('../views/users/UserFormView.vue'),
        meta: { title: 'Editar usuário', permission: 'users.manage' },
      },
      {
        path: 'settings/users/:id/view',
        name: 'settings-users-view',
        component: () => import('../views/users/UserFormView.vue'),
        meta: { title: 'Visualizar usuário', permission: 'users.read', mode: 'view' },
      },
      {
        path: 'settings/users/:id/permissions',
        name: 'settings-users-permissions',
        component: () => import('../views/users/UserPermissionsView.vue'),
        meta: { title: 'Permissões do usuário', permission: 'users.manage' },
      },
      {
        path: 'settings/access-levels',
        name: 'settings-access-levels',
        component: () => import('../views/access-levels/AccessLevelsView.vue'),
        meta: { title: 'Níveis de acesso', permission: 'roles.read' },
      },
      {
        path: 'settings/access-levels/new',
        name: 'settings-access-levels-new',
        component: () => import('../views/access-levels/AccessLevelFormView.vue'),
        meta: { title: 'Novo grupo de acesso', permission: 'roles.manage' },
      },
      {
        path: 'settings/access-levels/:id/edit',
        name: 'settings-access-levels-edit',
        component: () => import('../views/access-levels/AccessLevelFormView.vue'),
        meta: { title: 'Editar grupo de acesso', permission: 'roles.manage' },
      },
      { path: 'settings/sla', name: 'settings-sla', component: () => import('../views/ComingSoonView.vue'), meta: { title: 'SLA' } },
      { path: 'profile', name: 'profile', component: () => import('../views/ComingSoonView.vue'), meta: { title: 'Meu perfil' } },
    ],
  },
];

export default dashboardRouter;
