<script setup lang="ts">
import PageHeader from '../../components/common/PageHeader.vue'; import { useForm } from 'vee-validate'; import { toTypedSchema } from '@vee-validate/zod'; import { contactSchema } from '../../schemas/forms.schema';
import { computed, onMounted, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { createContact, getContact, updateContact } from '../../services/contacts.service'; import { listCompanies } from '../../services/companies.service'; import type { Company } from '../../types/company.types';
const { setValues, validate } = useForm({ validationSchema: toTypedSchema(contactSchema) });
const route = useRoute(); const router = useRouter(); const id = computed(() => route.params.id as string | undefined); const editing = computed(() => !!id.value); const readonly = computed(() => route.meta.mode === 'view'); const loading = ref(false); const saving = ref(false); const error = ref(''); const companies = ref<Company[]>([]); const form = ref({ name: '', email: '', phone: '', companyId: '' });
async function load() { loading.value = true; try { companies.value = await listCompanies(); if (id.value) { const item = await getContact(id.value); form.value = { name: item.name, email: item.email ?? '', phone: item.phone ?? '', companyId: '' }; } } catch { error.value = 'Não foi possível carregar o contato.'; } finally { loading.value = false; } }
async function save() { setValues(form.value as any); const result = await validate(); if (!result.valid) { error.value = 'Revise os campos destacados antes de salvar.'; return; } saving.value = true; try { const payload = { ...form.value, email: form.value.email || undefined, phone: form.value.phone || undefined, companyId: form.value.companyId || undefined }; if (editing.value) await updateContact(id.value!, payload); else await createContact(payload); router.push('/contacts'); } catch (err: any) { error.value = err?.response?.data?.message ?? 'Não foi possível salvar o contato.'; } finally { saving.value = false; } } onMounted(load);
</script>
<template><div><PageHeader :title="readonly ? 'Visualizar contato' : editing ? 'Editar contato' : 'Novo contato'" back-to="/contacts" /><v-alert v-if="error" type="error" density="compact" class="mb-4">{{ error }}</v-alert><v-card :loading="loading"><v-card-text><v-text-field v-model="form.name" label="Nome" :readonly="readonly" /><v-select v-model="form.companyId" :items="companies" item-title="name" item-value="id" label="Empresa" clearable :readonly="readonly" /><v-text-field v-model="form.email" label="E-mail" :readonly="readonly" /><v-text-field v-model="form.phone" label="Telefone" @update:model-value="form.phone = String($event).replace(/\D/g, '').slice(0, 11)" :readonly="readonly" /></v-card-text><v-card-actions><v-spacer /><v-btn variant="outlined" @click="router.push('/contacts')">{{ readonly ? 'Voltar' : 'Cancelar' }}</v-btn><v-btn v-if="!readonly" color="primary" variant="outlined" :loading="saving" :disabled="!form.name" @click="save">Salvar</v-btn></v-card-actions></v-card></div></template>
